export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const SELECT_TEAM = 'SELECT_TEAM';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';

export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
export const GET_RANKING_SUCCESS = 'GET_RANKING_SUCCESS';

export const START_AJAX_CALL = 'START_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
