export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const SELECT_TEAM = 'SELECT_TEAM';
export const GET_TEAM_SCHEDULE = 'GET_TEAM_SCHEDULE';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';

export const GET_TEAM_RESULTS = 'GET_TEAM_RESULTS';
export const GET_TEAM_RANKING = 'GET_TEAM_RANKING';

export const START_AJAX_CALL = 'START_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
