const CLUBCODE = 	'ZQ062BC';
const DUMMYTEAMS = [
  {
    "teamcode" : 993,
    "lokaleteamcode" : -1,
    "poulecode" : 24495,
    "teamnaam" : "C.S.V. Handbal DS1",
    "competitienaam" : "Dames Senioren",
    "klasse" : "2e Klasse",
    "poule" : "NW DS-2D V",
    "klassepoule" : "2e Klasse NW DS-2D V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "Senioren (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zaterdag speeldag",
    "more" : "team-indeling?teamcode=993&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2294,
    "lokaleteamcode" : -1,
    "poulecode" : 23751,
    "teamnaam" : "C.S.V. Handbal DS1",
    "competitienaam" : "Dames Senioren",
    "klasse" : "2e Klasse",
    "poule" : "NW-NH DS-2B Z",
    "klassepoule" : "2e Klasse NW-NH DS-2B Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "Senioren (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zaterdag speeldag",
    "more" : "team-indeling?teamcode=2294&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2302,
    "lokaleteamcode" : -1,
    "poulecode" : 24104,
    "teamnaam" : "C.S.V. Handbal DS2",
    "competitienaam" : "Dames Senioren",
    "klasse" : "Poule",
    "poule" : "NW-NH DS-07 Zaterdag",
    "klassepoule" : "Poule NW-NH DS-07 Zaterdag",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "Senioren (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zaterdag speeldag",
    "more" : "team-indeling?teamcode=2302&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2306,
    "lokaleteamcode" : -1,
    "poulecode" : 23719,
    "teamnaam" : "C.S.V. Handbal HS1",
    "competitienaam" : "Heren Senioren (L)",
    "klasse" : "Tweede Divisie",
    "poule" : "2D HS-A",
    "klassepoule" : "Tweede Divisie 2D HS-A",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "man",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "Senioren (H)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zaterdag speeldag",
    "more" : "team-indeling?teamcode=2306&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 1001,
    "lokaleteamcode" : -1,
    "poulecode" : 24060,
    "teamnaam" : "C.S.V. Handbal HS2",
    "competitienaam" : "Heren Senioren",
    "klasse" : "Poule",
    "poule" : "NW HS-04  V Zat.",
    "klassepoule" : "Poule NW HS-04  V Zat.",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "man",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "Senioren (H)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zaterdag speeldag",
    "more" : "team-indeling?teamcode=1001&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2307,
    "lokaleteamcode" : -1,
    "poulecode" : 24166,
    "teamnaam" : "C.S.V. Handbal HS2",
    "competitienaam" : "Heren Senioren",
    "klasse" : "Poule",
    "poule" : "NW HS-04 Z Zat.",
    "klassepoule" : "Poule NW HS-04 Z Zat.",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "man",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "Senioren (H)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zaterdag speeldag",
    "more" : "team-indeling?teamcode=2307&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 998,
    "lokaleteamcode" : -1,
    "poulecode" : 23975,
    "teamnaam" : "C.S.V. Handbal DB1",
    "competitienaam" : "Dames B-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH DB-06 V",
    "klassepoule" : "Poule NW-NH DB-06 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "B-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=998&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2299,
    "lokaleteamcode" : -1,
    "poulecode" : 24110,
    "teamnaam" : "C.S.V. Handbal DB1",
    "competitienaam" : "Dames B-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH DB-04 Z",
    "klassepoule" : "Poule NW-NH DB-04 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "B-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=2299&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2292,
    "lokaleteamcode" : -1,
    "poulecode" : 23958,
    "teamnaam" : "CSV/AenO HB1",
    "competitienaam" : "Heren B-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW HB-02 V",
    "klassepoule" : "Poule NW HB-02 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "man",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "B-Jeugd (H)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=2292&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2305,
    "lokaleteamcode" : -1,
    "poulecode" : 24848,
    "teamnaam" : "CSV/AenO HB1",
    "competitienaam" : "Heren B-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW HB-01 Z",
    "klassepoule" : "Poule NW HB-01 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "man",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "B-Jeugd (H)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=2305&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 22742,
    "lokaleteamcode" : -1,
    "poulecode" : 23993,
    "teamnaam" : "C.S.V. Handbal DC1#",
    "competitienaam" : "Dames C-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW-NH DC-06 V",
    "klassepoule" : "Poule NW-NH DC-06 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "C-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=22742&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 21823,
    "lokaleteamcode" : -1,
    "poulecode" : 24093,
    "teamnaam" : "C.S.V. Handbal DC1#",
    "competitienaam" : "Dames C-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH DC-04 Z",
    "klassepoule" : "Poule NW-NH DC-04 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "C-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=21823&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 6435,
    "lokaleteamcode" : -1,
    "poulecode" : 24064,
    "teamnaam" : "CSV/AenO HC1",
    "competitienaam" : "Heren C-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW HC-02 V",
    "klassepoule" : "Poule NW HC-02 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "man",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "C-Jeugd (H)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=6435&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2303,
    "lokaleteamcode" : -1,
    "poulecode" : 24170,
    "teamnaam" : "CSV/AenO HC1",
    "competitienaam" : "Heren C-Jeigd",
    "klasse" : "Poule",
    "poule" : "NW HC-02 Z",
    "klassepoule" : "Poule NW HC-02 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "man",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "C-Jeugd (H)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=2303&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 10542,
    "lokaleteamcode" : -1,
    "poulecode" : 24563,
    "teamnaam" : "C.S.V. Handbal DC2",
    "competitienaam" : "Dames C-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW-NH DC-10 V",
    "klassepoule" : "Poule NW-NH DC-10 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "C-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=10542&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2297,
    "lokaleteamcode" : -1,
    "poulecode" : 24092,
    "teamnaam" : "C.S.V. Handbal DC2",
    "competitienaam" : "Dames C-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH DC-07 Z",
    "klassepoule" : "Poule NW-NH DC-07 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "C-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=2297&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 994,
    "lokaleteamcode" : -1,
    "poulecode" : 24045,
    "teamnaam" : "C.S.V. Handbal D1",
    "competitienaam" : "D-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW-NH GD-07 V",
    "klassepoule" : "Poule NW-NH GD-07 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "D-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=994&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 2295,
    "lokaleteamcode" : -1,
    "poulecode" : 24137,
    "teamnaam" : "C.S.V. Handbal D1",
    "competitienaam" : "D-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH GD-11 Z",
    "klassepoule" : "Poule NW-NH GD-11 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "D-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=2295&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 15889,
    "lokaleteamcode" : -1,
    "poulecode" : 24638,
    "teamnaam" : "C.S.V. Handbal D2",
    "competitienaam" : "D-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW-NH GD-13 V",
    "klassepoule" : "Poule NW-NH GD-13 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "D-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=15889&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 15891,
    "lokaleteamcode" : -1,
    "poulecode" : 24137,
    "teamnaam" : "C.S.V. Handbal D2",
    "competitienaam" : "D-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH GD-11 Z",
    "klassepoule" : "Poule NW-NH GD-11 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "D-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=15891&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 22663,
    "lokaleteamcode" : -1,
    "poulecode" : 24015,
    "teamnaam" : "C.S.V. Handbal E1",
    "competitienaam" : "E-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW-NH GE-06 V",
    "klassepoule" : "Poule NW-NH GE-06 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "E-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=22663&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 21689,
    "lokaleteamcode" : -1,
    "poulecode" : 24072,
    "teamnaam" : "C.S.V. Handbal E1",
    "competitienaam" : "E-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH GE-06 Z",
    "klassepoule" : "Poule NW-NH GE-06 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "E-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=21689&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 23654,
    "lokaleteamcode" : -1,
    "poulecode" : 24016,
    "teamnaam" : "C.S.V. Handbal E2",
    "competitienaam" : "E-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW-NH GE-07 V",
    "klassepoule" : "Poule NW-NH GE-07 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "E-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=23654&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 23453,
    "lokaleteamcode" : -1,
    "poulecode" : 24078,
    "teamnaam" : "C.S.V. Handbal E2",
    "competitienaam" : "E-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH GE-09 Z",
    "klassepoule" : "Poule NW-NH GE-09 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "E-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=23453&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 4279,
    "lokaleteamcode" : -1,
    "poulecode" : 24566,
    "teamnaam" : "C.S.V. Handbal DMW1",
    "competitienaam" : "Dames Midweek",
    "klasse" : "Poule",
    "poule" : "NW-NH DMW-05 V",
    "klassepoule" : "Poule NW-NH DMW-05 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "Senioren (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "dinsdag speeldag",
    "more" : "team-indeling?teamcode=4279&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 4185,
    "lokaleteamcode" : -1,
    "poulecode" : 24485,
    "teamnaam" : "C.S.V. Handbal DMW1",
    "competitienaam" : "Dames Midweekr",
    "klasse" : "Poule",
    "poule" : "NW-NH DMW-05 Z",
    "klassepoule" : "Poule NW-NH DMW-05 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "vrouw",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "Senioren (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "dinsdag speeldag",
    "more" : "team-indeling?teamcode=4185&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 22718,
    "lokaleteamcode" : -1,
    "poulecode" : 23964,
    "teamnaam" : "C.S.V. Handbal F1#",
    "competitienaam" : "F-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW-GF-01 V",
    "klassepoule" : "Poule NW-GF-01 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "F-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=22718&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 21774,
    "lokaleteamcode" : -1,
    "poulecode" : 24128,
    "teamnaam" : "C.S.V. Handbal F1#",
    "competitienaam" : "F-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH GF-07 Z",
    "klassepoule" : "Poule NW-NH GF-07 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "F-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=21774&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 25099,
    "lokaleteamcode" : -1,
    "poulecode" : 23960,
    "teamnaam" : "C.S.V. Handbal F2",
    "competitienaam" : "F-Jeugd najaar",
    "klasse" : "Poule",
    "poule" : "NW-GF-11 V",
    "klassepoule" : "Poule NW-GF-11 V",
    "spelsoort" : "Veld",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "F-Jeugd (D)",
    "kalespelsoort" : "VE",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=25099&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 25286,
    "lokaleteamcode" : -1,
    "poulecode" : 24123,
    "teamnaam" : "C.S.V. Handbal F2",
    "competitienaam" : "F-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH GF-08 Z",
    "klassepoule" : "Poule NW-NH GF-08 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "F-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=25286&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : 27778,
    "lokaleteamcode" : -1,
    "poulecode" : 24921,
    "teamnaam" : "C.S.V. Handbal F3",
    "competitienaam" : "F-Jeugd",
    "klasse" : "Poule",
    "poule" : "NW-NH GF-10 Z",
    "klassepoule" : "Poule NW-NH GF-10 Z",
    "spelsoort" : "Zaal",
    "competitiesoort" : "regulier",
    "geslacht" : "onbekend",
    "teamsoort" : "bond",
    "leeftijdscategorie" : "F-Jeugd (D)",
    "kalespelsoort" : "ZA",
    "speeldag" : "",
    "speeldagteam" : "zondag speeldag",
    "more" : "team-indeling?teamcode=27778&lokaleteamcode=-1&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : -1,
    "lokaleteamcode" : 297,
    "poulecode" : -1,
    "teamnaam" : "B1",
    "competitienaam" : null,
    "klasse" : null,
    "poule" : null,
    "klassepoule" : "",
    "spelsoort" : "Veld WK",
    "competitiesoort" : "-",
    "geslacht" : "man",
    "teamsoort" : "lokaal",
    "leeftijdscategorie" : "",
    "kalespelsoort" : "VE",
    "speeldag" : "WK",
    "speeldagteam" : "WK",
    "more" : "team-indeling?teamcode=-1&lokaleteamcode=297&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : -1,
    "lokaleteamcode" : 302,
    "poulecode" : -1,
    "teamnaam" : "D1",
    "competitienaam" : null,
    "klasse" : null,
    "poule" : null,
    "klassepoule" : "",
    "spelsoort" : "Veld WK",
    "competitiesoort" : "-",
    "geslacht" : "gemengd",
    "teamsoort" : "lokaal",
    "leeftijdscategorie" : "",
    "kalespelsoort" : "VE",
    "speeldag" : "WK",
    "speeldagteam" : "WK",
    "more" : "team-indeling?teamcode=-1&lokaleteamcode=302&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : -1,
    "lokaleteamcode" : 313,
    "poulecode" : -1,
    "teamnaam" : "1",
    "competitienaam" : null,
    "klasse" : null,
    "poule" : null,
    "klassepoule" : "",
    "spelsoort" : "Zaal WK",
    "competitiesoort" : "-",
    "geslacht" : "vrouw",
    "teamsoort" : "lokaal",
    "leeftijdscategorie" : "",
    "kalespelsoort" : "ZA",
    "speeldag" : "WK",
    "speeldagteam" : "WK",
    "more" : "team-indeling?teamcode=-1&lokaleteamcode=313&gebruiklokaleteamgegevens=NEE"
  }, {
    "teamcode" : -1,
    "lokaleteamcode" : 286,
    "poulecode" : -1,
    "teamnaam" : "D1",
    "competitienaam" : null,
    "klasse" : null,
    "poule" : null,
    "klassepoule" : "",
    "spelsoort" : "Zaal WK",
    "competitiesoort" : "-",
    "geslacht" : "gemengd",
    "teamsoort" : "lokaal",
    "leeftijdscategorie" : "",
    "kalespelsoort" : "ZA",
    "speeldag" : "WK",
    "speeldagteam" : "WK",
    "more" : "team-indeling?teamcode=-1&lokaleteamcode=286&gebruiklokaleteamgegevens=NEE"
  }
];
